---
esphome:
  name: ${device}

esp8266:
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/sensors.yaml
<<: !include common/switches.yaml
<<: !include common/logger.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: ${name}
    output: relay_1
    id: light_1

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: light_1
