---
language: python
python:
  - "2.7"
before_install:
  - mv .travis-secrets.yaml secrets.yaml
install:
  - pip install yamllint
  - pip install esphomeyaml
script:
  - yamllint .
  - esphomeyaml smartmeter.yaml config
  - esphomeyaml smartmeter.yaml compile
