---
dist: bionic
language: minimal
python:
  - "3.7"
cache: pip
env:
  matrix:
    - DEVICE=minimal
    - DEVICE=attic_1
    - DEVICE=bedroom_1
    - DEVICE=bedroom_2
    - DEVICE=garage
    - DEVICE=living_1
    - DEVICE=smartmeter
    - DEVICE=ventilation
    - DEVICE=veranda_lights
install:
  - . install.sh
  - mv .travis-secrets.yaml secrets.yaml
  - mv common/.travis-secrets.yaml common/secrets.yaml
script: esphome ${DEVICE}.yaml compile
jobs:
  include:
    - stage: lint
      install: pip install yamllint
      script: yamllint .
      matrix:
        exclude:
          - env: DEVICE=attic_1
          - env: DEVICE=bedroom_1
          - env: DEVICE=bedroom_2
          - env: DEVICE=garage
          - env: DEVICE=living_1
          - env: DEVICE=smartmeter
          - env: DEVICE=ventilation
          - env: DEVICE=veranda_lights
