---
dist: bionic
language: python
python: 3.7
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/$DEVICE
git:
  depth: 3
env:
  matrix:
    - DEVICE=minimal
    - DEVICE=attic_1
    - DEVICE=bedroom_1
    - DEVICE=bedroom_2
    - DEVICE=garage
    - DEVICE=living_1
    - DEVICE=smartmeter
    - DEVICE=ventilation
    - DEVICE=veranda_lights
install:
  - . install.sh
  - mv .travis-secrets.yaml secrets.yaml
  - mv common/.travis-secrets.yaml common/secrets.yaml
script:
  - esphome ${DEVICE}.yaml compile
