---
dist: xenial
language: python
python:
  - "3.7"
before_install:
  - mv components/.travis-secrets.yaml components/secrets.yaml
install:
  - pip install -U
    https://github.com/platformio/platformio-core/archive/develop.zip
  - pip install yamllint
  - pip install esphome
script:
  - yamllint .
  - esphome smartmeter.yaml compile
  - esphome bedroom_2.yaml compile
  - esphome living_1.yaml compile
  - esphome ventilation.yaml compile
  - esphome garage.yaml compile
  - esphome veranda_wcd.yaml compile
