---
dist: xenial
language: python
python:
  - "3.7"
before_install:
  - mv common/.travis-secrets.yaml common/secrets.yaml
install:
  - . install.sh
script:
  - yamllint .
  - esphome minimal.yaml compile
  - esphome test.yaml compile
  - esphome attic_1.yaml compile
  - esphome bedroom_1.yaml compile
  - esphome bedroom_2.yaml compile
  - esphome garage.yaml compile
  - esphome living_1.yaml compile
  - esphome smartmeter.yaml compile
  - esphome ventilation.yaml compile
  - esphome veranda_wcd.yaml compile
