---
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
before_install:
  - mv .travis-secrets.yaml secrets.yaml
install:
  - pip install -U
    https://github.com/platformio/platformio-core/archive/develop.zip
  - pip install yamllint
  - pip install esphomeyaml
script:
  - yamllint .
  - esphomeyaml smartmeter.yaml config
  - esphomeyaml smartmeter.yaml compile
