---
dist: xenial
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: lint
      install:
        - pip install yamllint
      script: yamllint .
    - stage: compile
      env:
        - DEVICE=minimal
        - DEVICE=attic_1
        - DEVICE=bedroom_1
        - DEVICE=bedroom_2
        - DEVICE=garage
        - DEVICE=living_1
        - DEVICE=smartmeter
        - DEVICE=ventilation
        - DEVICE=veranda_lights
      install:
        - . install.sh
        - mv .travis-secrets.yaml secrets.yaml
        - mv common/.travis-secrets.yaml common/secrets.yaml
      script: esphome ${DEVICE}.yaml compile
