---
dist: xenial
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: lint
      install: pip install yamllint
      script: yamllint .
    - stage: compile
      matrix:
        fats_finish: true
        include:
          - env: DEVICE=minimal
          - env: DEVICE=attic_1
          - env: DEVICE=bedroom_1
          - env: DEVICE=bedroom_2
          - env: DEVICE=garage
          - env: DEVICE=living_1
          - env: DEVICE=smartmeter
          - env: DEVICE=ventilation
          - env: DEVICE=veranda_lights
      install:
        - . install.sh
        - mv .travis-secrets.yaml secrets.yaml
        - mv common/.travis-secrets.yaml common/secrets.yaml
      script: esphome ${DEVICE}.yaml compile
