---
dist: xenial
language: python
python:
  - "3.7"
before_install:
  - mv .travis-secrets.yaml secrets.yaml
install:
  - pip install -U
    https://github.com/platformio/platformio-core/archive/develop.zip
  - pip install yamllint
  - pip install esphome
script:
  - yamllint *.yaml
  - esphome smartmeter.yaml config
  - esphome bedroom_2.yaml config
  - esphome living_1.yaml config
  - esphome smartmeter.yaml compile
  - esphome bedroom_2.yaml compile
  - esphome living_1.yaml compile
