---
substitutions:
  device: attic_1
  name: Zolder
  reboot_timeout: 7d

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  arduino_version: latest

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger: !include common/logger.yaml
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml
sensor: !include common/sensors.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: pc
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: printer
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: bureaulamp
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: ${name} Bureaulamp
    output: relay_3
    id: bureaulamp

switch:
  - !include common/switch/restart.yaml
  - platform: output
    name: ${name} PC
    output: relay_1
    id: pc
    icon: mdi:laptop
  - platform: output
    name: ${name} Printer
    output: relay_2
    id: printer
    icon: mdi:printer
