---
substitutions:
  device: attic_1
  name: Zolder
  reboot_timeout: 14d

esphome:
  name: ${device}
  platform: ESP8266
  platformio_options:
    lib_ldf_mode: deep
  board: esp01_1m
  board_flash_mode: dout

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger:
  level: INFO
  baud_rate: 0
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

i2c:
  sda: GPIO2
  scl: RX

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: bme280
    temperature:
      name: ${name} Temperatuur
    pressure:
      name: ${name} Luchtdruk
    humidity:
      name: ${name} Luchtvochtigheid
    address: 0x76
    update_interval: 10min

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: pc
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: printer
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: bureaulamp
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true

output:
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: ${name} Bureaulamp
    output: relay_3
    id: bureaulamp

switch:
  - !include common/switch/restart.yaml
  - platform: gpio
    name: ${name} PC
    pin: GPIO12
    id: pc
    icon: mdi:laptop
  - platform: gpio
    name: ${name} Printer
    pin: GPIO5
    id: printer
    icon: mdi:printer
