---
substitutions:
  device: bedroom_2
  name: Slaapkamer Achterwand
  reboot_timeout: 14d
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/sensors.yaml
<<: !include common/switches.yaml
logger:
  level: INFO
  baud_rate: 0

remote_receiver:
  <<: !include common/rf_receiver.yaml
  pin: RX

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: light_1
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    id: rf_button_bedroom_back_wall
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_bedroom_back_wall
    on_press:
      then:
        - light.toggle: light_1
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    name: RF Button TV Slaapkamer
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_bedroom_tv
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    name: RF Button Watch TV
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_watch_tv
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    name: RF Button Watch Media
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_watch_media
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    name: RF Button Listen Music
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_listen_music
  - platform: remote_receiver
    <<: !include common/rf_receiver_sensor.yaml
    name: RF Button All Off
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_all_off

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: ${name}
    output: relay_1
    id: light_1
