---
substitutions:
  device: bedroom_2
  name: Slaapkamer Achterwand

esphomeyaml:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  domain: !secret home_domain
  fast_connect: true
  reboot_timeout: 7d

api:
  password: !secret api_password
  reboot_timeout: 7d

logger:
  level: INFO

ota:

web_server:

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    name: ${name} Uptime Sensor

text_sensor:
  - platform: version
    name: ${name} ESPHome Version

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button
    on_press:
      then:
        - light.toggle: ${device}_light

output:
  - platform: gpio
    pin: GPIO12
    id: gpio_12
  - platform: esp8266_pwm
    id: ${device}_green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: binary
    name: ${name}
    output: gpio_12
    id: ${device}_light
  - platform: monochromatic
    name: ${name} Green LED
    output: ${device}_green_led

switch:
  - platform: restart
    name: ${name} Restart
