---
substitutions:
  device: bedroom_2
  name: Slaapkamer Achterwand
  reboot_timeout: 14d

esphome:
  name: ${device}
  platform: ESP8266
  platformio_options:
    lib_ldf_mode: deep
  board: esp01_1m
  board_flash_mode: dout

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger:
  level: INFO
  baud_rate: 0
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml
sensor: !include common/sensors.yaml
switch: !include common/switches.yaml

remote_receiver:
  pin: RX
  dump:
    - rc_switch
  tolerance: 60%
  filter: 4us
  idle: 4ms

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: light_1
  - platform: remote_receiver
    id: rf_button_bedroom_back_wall
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_bedroom_back_wall
    filters:
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: light_1
  - platform: remote_receiver
    name: RF Button TV Slaapkamer
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_bedroom_tv
    filters:
      - delayed_off: 100ms

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: ${name}
    output: relay_1
    id: light_1
