---
substitutions:
  device: bedroom_2
  name: Slaapkamer Achterwand
  reboot_timeout: 7d

esphomeyaml:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  domain: !secret home_domain
  fast_connect: true
  reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret api_password

api:
  password: !secret api_password
  reboot_timeout: ${reboot_timeout}

logger:
  level: INFO

ota:

web_server:

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    name: ${name} Uptime Sensor

text_sensor:
  - platform: version
    name: ${name} ESPHome Version

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button
    on_press:
      then:
        - light.toggle: ${device}_light

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: ${name}
    output: relay_1
    id: ${device}_light

switch:
  - platform: restart
    name: ${name} Restart
