---
substitutions:
  device: bedroom_2
  name: Slaapkamer Achterwand
  reboot_timeout: 7d

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi: !include components/wifi.yaml
api: !include components/api.yaml
logger: !include components/logger.yaml
ota:
web_server:

sensor:
  - !include sensors/wifi-signal.yaml
  - !include sensors/uptime.yaml

text_sensor:
  - !include text_sensors/version.yaml
  - !include text_sensors/pretty-uptime.yaml
  - !include text_sensors/wifi-info.yaml

binary_sensor:
  - !include binary_sensors/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: light

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: ${name}
    output: relay_1
    id: light

switch:
  - !include switches/restart.yaml
