---
substitutions:
  device: garage
  name: Garage
  reboot_timeout: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini_pro
  on_boot:
  - priority: 90
    then:
    - output.turn_on: dht_supply

wifi: !include components/wifi.yaml
api: !include components/api.yaml
logger: !include components/logger.yaml
ota:
web_server:

status_led:
  pin:
    number: LED
    inverted: true

dallas:
  - pin: D7

output:
  - platform: gpio
    pin: D8
    id: dallas_gnd
  - platform: gpio
    pin: D1
    id: dht_gnd
  - platform: gpio
    pin: D2
    id: dht_supply

sensor:
  - !include sensors/wifi-signal.yaml
  - !include sensors/uptime.yaml
  - platform: dallas
    address: 0xDE011438B6F4AA28
    name: Buiten Temperatuur
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: ${name} Temperatuur
    humidity:
      name: ${name} Luchtvochtigheid

text_sensor:
  - !include text_sensors/version.yaml
  - !include text_sensors/pretty-uptime.yaml
  - !include text_sensors/wifi-info.yaml

binary_sensor:
  - !include binary_sensors/status.yaml

switch:
  - !include switches/restart.yaml
