---
substitutions:
  device: garage
  name: Garage
  reboot_timeout: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini_pro
  arduino_version: latest
  on_boot:
    - priority: 90
      then:
        - output.turn_on: dht_supply

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger: !include common/logger.yaml
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml
binary_sensor: !include common/binary_sensors.yaml
switch: !include common/switches.yaml

status_led:
  pin:
    number: LED
    inverted: true

dallas:
  - pin: D7

output:
  - platform: gpio
    pin: D8
    id: dallas_gnd
  - platform: gpio
    pin: D1
    id: dht_gnd
  - platform: gpio
    pin: D2
    id: dht_supply

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: dallas
    address: 0xDE011438B6F4AA28
    name: Buiten Temperatuur
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: ${name} Temperatuur
    humidity:
      name: ${name} Luchtvochtigheid
