---
substitutions:
  device: living_1
  name: TV Meubel
  location: Woonkamer
  reboot_timeout: 14d

esphome:
  name: ${device}
  platform: ESP8266
  platformio_options:
    lib_ldf_mode: deep
  board: esp01_1m
  board_flash_mode: dout

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger:
  level: INFO
  baud_rate: 0
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

i2c:
  sda: GPIO2
  scl: RX

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: bme280
    temperature:
      name: ${location} Temperatuur
    pressure:
      name: ${location} Luchtdruk
    humidity:
      name: ${location} Luchtvochtigheid
    address: 0x76
    update_interval: 10min

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: tv
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: receiver
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: spruitje
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: mediaplayer

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: ${name} Spruitje
    output: relay_3
    id: spruitje

switch:
  - !include common/switch/restart.yaml
  - platform: output
    name: ${name} TV
    output: relay_1
    id: tv
  - platform: output
    name: ${name} Receiver
    output: relay_2
    id: receiver
  - platform: output
    name: ${name} Mediaplayer
    output: relay_4
    id: mediaplayer
