---
substitutions:
  device: living_1
  name: TV Meubel
  reboot_timeout: 7d

esphomeyaml:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  domain: !secret home_domain
  fast_connect: true
  reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret api_password

api:
  password: !secret api_password
  reboot_timeout: ${reboot_timeout}

logger:
  level: INFO

ota:

web_server:

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    name: ${name} Uptime Sensor

text_sensor:
  - platform: version
    name: ${name} ESPHome Version

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button 1
    on_press:
      then:
        - switch.toggle: tv
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button 2
    on_press:
      then:
        - switch.toggle: receiver
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button 3
    on_press:
      then:
        - light.toggle: spruitje
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: ${name} Button 4
    on_press:
      then:
        - switch.toggle: mediaplayer

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: ${name} Spruitje
    output: relay_3
    id: spruitje

switch:
  - platform: output
    name: ${name} TV
    output: relay_1
    id: tv
  - platform: output
    name: ${name} Receiver
    output: relay_2
    id: receiver
  - platform: output
    name: ${name} Mediaplayer
    output: relay_4
    id: mediaplayer
  - platform: restart
    name: ${name} Restart
