---
substitutions:
  device: living_1
  name: TV Meubel
  reboot_timeout: 7d

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  fast_connect: true
  reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret api_password

api:
  password: !secret api_password
  reboot_timeout: ${reboot_timeout}

logger:
  level: INFO

ota:

web_server:

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    id: uptime

text_sensor:
  - platform: version
    name: ${name} ESPHome Version
  - platform: template
    name: ${name} Uptime
    icon: mdi:timer
    lambda: |-
      int up = id(uptime).state;
      char result[16];
      sprintf(result, "%dd %02d:%02d:%02d", up / 86400, (up % 86400) / 3600,
                                            (up % 3600) / 60, up % 60);
      return std::string(result);

binary_sensor:
  - platform: status
    name: ${name} Status
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: tv
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: receiver
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.toggle: spruitje
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: mediaplayer

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: ${name} Spruitje
    output: relay_3
    id: spruitje

switch:
  - platform: output
    name: ${name} TV
    output: relay_1
    id: tv
  - platform: output
    name: ${name} Receiver
    output: relay_2
    id: receiver
  - platform: output
    name: ${name} Mediaplayer
    output: relay_4
    id: mediaplayer
  - platform: restart
    name: ${name} Restart
