---
substitutions:
  device: smartmeter
  name: Smartmeter

esphomeyaml:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - smartmeter.h

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  domain: !secret home_domain
  fast_connect: true
  reboot_timeout: 5min

api:
  password: !secret api_password

logger:
  level: INFO

ota:

web_server:

status_led:
  pin:
    number: D4
    inverted: true

switch:
  - platform: restart
    name: ${name} Restart

sensor:
  - platform: wifi_signal
    name: ${name} WiFi Signal
  - platform: uptime
    name: ${name} Uptime Sensor
  - platform: dht
    model: DHT22
    pin: GPIO14
    temperature:
      name: Meterkast Temperatuur
    humidity:
      name: Meterkast Luchtvochtigheid
  - platform: custom
    lambda: |-
      auto smartmeter_sensor = new SmartMeterSensor(
          (char *)"Smartmeter Power Consumption", 12, 10000, 1000.0);
      App.register_component(smartmeter_sensor);
      return {smartmeter_sensor};
    sensors:
      name: ${name} Power Consumption

text_sensor:
  - platform: version
    name: ${name} ESPHome Version
