---
substitutions:
  device: smartmeter
  name: Smartmeter
  reboot_timeout: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - smartmeter.h

wifi: !include components/wifi.yaml
api: !include components/api.yaml
logger: !include components/logger.yaml
ota:
web_server:

status_led:
  pin:
    number: D4
    inverted: true

sensor:
  - !include sensors/wifi-signal.yaml
  - !include sensors/uptime.yaml
  - platform: dht
    model: DHT22
    pin: GPIO14
    temperature:
      name: Meterkast Temperatuur
    humidity:
      name: Meterkast Luchtvochtigheid
  - platform: custom
    lambda: |-
      auto smartmeter_sensor = new SmartMeterSensor(
          (char *)"Smartmeter Power Consumption", 12, 10000, 1000.0);
      App.register_component(smartmeter_sensor);
      return {smartmeter_sensor};
    sensors:
      name: ${name} Power Consumption

text_sensor:
  - !include text_sensors/version.yaml
  - !include text_sensors/pretty-uptime.yaml

binary_sensor:
  - !include binary_sensors/status.yaml

switch:
  - !include switches/restart.yaml
