---
substitutions:
  device: smartmeter
  name: Smartmeter
  location: Meterkast
  reboot_timeout: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini_pro
  includes:
    - smartmeter.h
  on_boot:
    - priority: 90
      then:
        - output.turn_on: sm_supply
        - output.turn_off: bme_gnd

wifi: !include components/wifi.yaml
api: !include components/api.yaml
logger: !include components/logger.yaml
ota:
web_server:

status_led:
  pin:
    number: D4
    inverted: true

i2c:
  sda: D2
  scl: D1

output:
  - platform: gpio
    pin: D3
    id: bme_gnd
  - platform: gpio
    pin: D5
    id: sm_gnd
  - platform: gpio
    pin: D7
    id: sm_supply

sensor:
  - !include sensors/wifi-signal.yaml
  - !include sensors/uptime.yaml
  - platform: bme280
    temperature:
      name: ${location} Temperatuur
    pressure:
      name: ${location} Luchtdruk
    humidity:
      name: ${location} Luchtvochtigheid
    address: 0x76
  - platform: custom
    lambda: |-
      auto smartmeter_sensor = new SmartMeterSensor(12, 10000, 1000.0);
      App.register_component(smartmeter_sensor);
      return {
        smartmeter_sensor->power_consumption_sensor,
        smartmeter_sensor->total_consumption_sensor
      };
    sensors:
      - name: ${name} Power Consumption
        unit_of_measurement: kW
        accuracy_decimals: 3
        icon: mdi:power-plug
      - name: ${name} Total Consumption
        unit_of_measurement: kWh
        accuracy_decimals: 3
        icon: mdi:sigma

text_sensor:
  - !include text_sensors/version.yaml
  - !include text_sensors/pretty-uptime.yaml
  - !include text_sensors/wifi-info.yaml

binary_sensor:
  - !include binary_sensors/status.yaml

switch:
  - !include switches/restart.yaml
