---
esphomeyaml:
  name: smartmeter
  platform: ESP8266
  board: nodemcuv2
  includes:
    - smartmeter.h

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password

api:
  password: !secret api_password

status_led:
  pin:
    number: D4
    inverted: true

logger:
  level: INFO

ota:

sensor:
  - platform: wifi_signal
    name: Smartmeter WiFi Signal
  - platform: uptime
    name: Smartmeter Uptime Sensor
  - platform: dht
    model: DHT22
    pin: GPIO14
    temperature:
      name: Meterkast Temperatuur
    humidity:
      name: Meterkast Luchtvochtigheid
  - platform: custom
    lambda: |-
      auto smartmeter_sensor = new SmartMeterSensor(
          (char *)"Smartmeter Power Consumption", 12, 10000, 1000.0);
      App.register_component(smartmeter_sensor);
      return {smartmeter_sensor};
    sensors:
      name: Smartmeter Power Consumption
