---
substitutions:
  device: test
  name: Test
  reboot_timeout: 14d

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    lib_ldf_mode: deep

wifi: !include common/wifi.yaml
api: !include common/api.yaml
logger:
  level: DEBUG
ota: !include common/ota.yaml
web_server: !include common/web_server.yaml
text_sensor: !include common/text_sensors.yaml
switch: !include common/switches.yaml
sensor: !include common/sensors.yaml

status_led:
  pin:
    number: LED
    inverted: true

remote_receiver:
  pin: D6
  dump:
    - rc_switch
  tolerance: 60%
  filter: 4us
  idle: 4ms

binary_sensor:
  - platform: remote_receiver
    name: RF Button Test
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code_test
    filters:
      - delayed_off: 100ms
